### ISSUE TITLE
Create pull-down menu for travel

### ISSUE THREAD

**Issue by rahyoung** [onewaypath/onewaypath.com-bootstrap#9]
- [x] ensure you are working on the latest version of dev1 branch
- [x] Please refer to issue #8. 
- [x] Change the menu item for "Photo Gallery" to "Travel"
- [x] The structure of the Travel menu should be:
   - Travel
       - Colour Photo Gallery (links to photo-gallery-colour.html)
       - Black & White Photo Gallery (links to photo-gallery-bw.html)
 - [x] push your changes to dev1 branch with a commit for only this issue

**Comment by dynamicdreamz1** [comment]
Create pull-down menu for travel #9 **=> Done and push on dev1**

**Comment by rahyoung** [comment]
- [x] Fix per below comment from #8

https://github.com/onewaypath/onewaypath.com-bootstrap/issues/8#issuecomment-1122248651

**Comment by dynamicdreamz1** [comment]
Fix per below comment from https://github.com/onewaypath/onewaypath.com-bootstrap/issues/8 **=> Done**

**Comment by rahyoung** [comment]
- [x] Please fix per my comments on #8

**Comment by dynamicdreamz1** [comment]
This is done => https://github.com/onewaypath/onewaypath.com-bootstrap/commit/74f64efb1dea3881b7778b67dc8d709e8f4a7a5f
https://github.com/onewaypath/onewaypath.com-bootstrap/issues/8 => please chack
